config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :finishings
  resources :materials
  resources :colors
  resources :articles
  get 'about', to: 'pages#about'
  get 'contact', to: 'pages#contact'

  root "pages#home"
end

app/models/finishing.rb
class Finishing < ApplicationRecord
end

app/controllers/finishings_controller.rb
class FinishingsController < ApplicationController
  before_action :set_finishing, only: %i[ show edit update destroy ]

  # GET /finishings or /finishings.json
  def index
    @finishings = Finishing.all
  end

  # GET /finishings/1 or /finishings/1.json
  def show
  end

  # GET /finishings/new
  def new
    @finishing = Finishing.new
  end

  # GET /finishings/1/edit
  def edit
  end

  # POST /finishings or /finishings.json
  def create
    @finishing = Finishing.new(finishing_params)

    respond_to do |format|
      if @finishing.save
        format.html { redirect_to finishing_url(@finishing), notice: "Finishing was successfully created." }
        format.json { render :show, status: :created, location: @finishing }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @finishing.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /finishings/1 or /finishings/1.json
  def update
    respond_to do |format|
      if @finishing.update(finishing_params)
        format.html { redirect_to finishing_url(@finishing), notice: "Finishing was successfully updated." }
        format.json { render :show, status: :ok, location: @finishing }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @finishing.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /finishings/1 or /finishings/1.json
  def destroy
    @finishing.destroy

    respond_to do |format|
      format.html { redirect_to finishings_url, notice: "Finishing was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_finishing
      @finishing = Finishing.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def finishing_params
      params.require(:finishing).permit(:title)
    end
end

app/helpers/finishings_helper.rb
module FinishingsHelper
end

app/views/finishings/_finishing.html.erb
<div id="<%= dom_id finishing %>">
  <p>
    <strong>Title:</strong>
    <%= finishing.title %>
  </p>

</div>

app/views/finishings/_form.html.erb
<%= form_with(model: finishing) do |form| %>
  <% if finishing.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(finishing.errors.count, "error") %> prohibited this finishing from being saved:</h2>

      <ul>
        <% finishing.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/finishings/edit.html.erb
<h1>Editing finishing</h1>

<%= render "form", finishing: @finishing %>

<br>

<div>
  <%= link_to "Show this finishing", @finishing %> |
  <%= link_to "Back to finishings", finishings_path %>
</div>

app/views/finishings/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Finishings</h1>

<div id="finishings">
  <% @finishings.each do |finishing| %>
    <%= render finishing %>
    <p>
      <%= link_to "Show this finishing", finishing %>
    </p>
  <% end %>
</div>

<%= link_to "New finishing", new_finishing_path %>

app/views/finishings/new.html.erb
<h1>New finishing</h1>

<%= render "form", finishing: @finishing %>

<br>

<div>
  <%= link_to "Back to finishings", finishings_path %>
</div>

app/views/finishings/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @finishing %>

<div>
  <%= link_to "Edit this finishing", edit_finishing_path(@finishing) %> |
  <%= link_to "Back to finishings", finishings_path %>

  <%= button_to "Destroy this finishing", @finishing, method: :delete %>
</div>