config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :finishings
  resources :materials
  resources :colors
  resources :articles
  get 'about', to: 'pages#about'
  get 'contact', to: 'pages#contact'

  root "pages#home"
end

app/models/color.rb
class Color < ApplicationRecord
    has_and_belongs_to_many :finishings, class_name: "Color::Finishing"
    has_one_attached :image
    has_many_attached :pictures
end

app/controllers/colors_controller.rb
class ColorsController < ApplicationController
  before_action :set_color, only: %i[ show edit update destroy ]

  # GET /colors or /colors.json
  def index
    @colors = Color.all
  end

  # GET /colors/1 or /colors/1.json
  def show
  end

  # GET /colors/new
  def new
    @color = Color.new
  end

  # GET /colors/1/edit
  def edit
  end

  # POST /colors or /colors.json
  def create
    @color = Color.new(color_params)

    respond_to do |format|
      if @color.save
        format.html { redirect_to color_url(@color), notice: "Color was successfully created." }
        format.json { render :show, status: :created, location: @color }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @color.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /colors/1 or /colors/1.json
  def update
    respond_to do |format|
      if @color.update(color_params)
        format.html { redirect_to color_url(@color), notice: "Color was successfully updated." }
        format.json { render :show, status: :ok, location: @color }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @color.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /colors/1 or /colors/1.json
  def destroy
    @color.destroy

    respond_to do |format|
      format.html { redirect_to colors_url, notice: "Color was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_color
      @color = Color.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def color_params
      params.require(:color).permit(:title, :description, :min, :max, :price, {finishing_ids: [] })
    end
end

app/helpers/colors_helper.rb
module ColorsHelper
end

app/views/colors/_color.html.erb
<div id="<%= dom_id color %>">
  <p>
    <strong>Title:</strong>
    <%= color.title %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= color.description %>
  </p>

  <p>
    <strong>Min:</strong>
    <%= color.min %>
  </p>

  <p>
    <strong>Max:</strong>
    <%= color.max %>
  </p>

  <p>
    <strong>Price:</strong>
    <%= color.price %>
  </p>

</div>

app/views/colors/_form.html.erb
<%= form_with(model: color) do |form| %>
  <% if color.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(color.errors.count, "error") %> prohibited this color from being saved:</h2>

      <ul>
        <% color.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_area :description %>
  </div>

  <div>
    <%= form.label :min, style: "display: block" %>
    <%= form.number_field :min %>
  </div>

  <div>
    <%= form.label :max, style: "display: block" %>
    <%= form.number_field :max %>
  </div>

  <div>
    <%= form.label :price, style: "display: block" %>
    <%= form.number_field :price %>
  </div>

  <div>
    <%= form.collection_check_boxes :finishing_ids, Finishing.all, :id, :title, {}, {:multiple => true } %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/colors/edit.html.erb
<h1>Editing color</h1>

<%= render "form", color: @color %>

<br>

<div>
  <%= link_to "Show this color", @color %> |
  <%= link_to "Back to colors", colors_path %>
</div>

app/views/colors/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Colors</h1>

<div id="colors">
  <% @colors.each do |color| %>
    <%= render color %>
    <p>
      <%= link_to "Show this color", color %>
    </p>
  <% end %>
</div>

<%= link_to "New color", new_color_path %>

app/views/colors/new.html.erb
<h1>New color</h1>

<%= render "form", color: @color %>

<br>

<div>
  <%= link_to "Back to colors", colors_path %>
</div>

app/views/colors/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @color %>

<div>
  <%= link_to "Edit this color", edit_color_path(@color) %> |
  <%= link_to "Back to colors", colors_path %>

  <%= button_to "Destroy this color", @color, method: :delete %>
</div>