config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :finishings
  resources :materials
  resources :colors
  resources :articles
  get 'about', to: 'pages#about'
  get 'contact', to: 'pages#contact'

  root "pages#home"
end

app/models/material.rb
class Material < ApplicationRecord
    has_and_belongs_to_many :colors, class_name: "Material::Color"
    has_one_attached :image
    has_many_attached :pictures
end

app/controllers/materials_controller.rb
class MaterialsController < ApplicationController
  before_action :set_material, only: %i[ show edit update destroy ]

  # GET /materials or /materials.json
  def index
    @materials = Material.all
  end

  # GET /materials/1 or /materials/1.json
  def show
  end

  # GET /materials/new
  def new
    @material = Material.new
  end

  # GET /materials/1/edit
  def edit
  end

  # POST /materials or /materials.json
  def create
    @material = Material.new(material_params)

    respond_to do |format|
      if @material.save
        format.html { redirect_to material_url(@material), notice: "Material was successfully created." }
        format.json { render :show, status: :created, location: @material }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @material.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /materials/1 or /materials/1.json
  def update
    respond_to do |format|
      if @material.update(material_params)
        format.html { redirect_to material_url(@material), notice: "Material was successfully updated." }
        format.json { render :show, status: :ok, location: @material }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @material.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /materials/1 or /materials/1.json
  def destroy
    @material.destroy

    respond_to do |format|
      format.html { redirect_to materials_url, notice: "Material was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_material
      @material = Material.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def material_params
      params.require(:material).permit(:title, :description)
    end
end

app/helpers/materials_helper.rb
module MaterialsHelper
end

app/views/materials/_form.html.erb
<%= form_with(model: material) do |form| %>
  <% if material.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(material.errors.count, "error") %> prohibited this material from being saved:</h2>

      <ul>
        <% material.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_field :description %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/materials/_material.html.erb
<div id="<%= dom_id material %>">

  <div class="container marketing">
    <div class="row featurette">
      <div class="col-md-7">
        <h2 class="featurette-heading fw-normal lh-1"><%= material.title %></h2>
        <p class="lead trix-content"><%= material.description %></p>
      </div>
      <div class="col-md-5">
        <%= image_tag(material.image, class: "featurette-image img-fluid mx-auto",width: "500", height: "500", role: "img", preserveAspectRatio: "xMidYMid slice", focusable: "false") %>
      </div>
    </div>
  </div>

</div>

app/views/materials/edit.html.erb
<h1>Editing material</h1>

<%= render "form", material: @material %>

<br>

<div>
  <%= link_to "Show this material", @material %> |
  <%= link_to "Back to materials", materials_path %>
</div>

app/views/materials/index.html.erb
<p style="color: green"><%= notice %></p>

<h1 class="text-center">Liste des Materiaux</h1>

<div class="container">
  <div class="row">
  <% @materials.each do |material| %>
    <div class="col-12 col-md-4">
    <%= link_to material_path(material) do %>
      <div class="">
          <%= image_tag(material.image, :class => "img-fluid", id: "img-custom") %>
      </div>
      <h2  class="text-center"><%= material.title %></h2>
    <% end %>
    </div>
  <% end %>  
  </div>
</div>

app/views/materials/new.html.erb
<h1>New material</h1>

<%= render "form", material: @material %>

<br>

<div>
  <%= link_to "Back to materials", materials_path %>
</div>

app/views/materials/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @material %>

<div class="container">
  <%= link_to "Back", materials_path %>

</div>